# Stage 1 
FROM node:20 as builder
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
RUN npm run build  
# Creates a production build of the React app


# Stage 2
FROM nginx:alpine
# Remove the default Nginx config from container 
RUN rm /etc/nginx/conf.d/default.conf


# This is to help with SPA routing, so that Nginx serves index.html for all routes
COPY fup_spa.conf /etc/nginx/conf.d/default.conf

# Copy the built files from the builder stage into Nginx's web root
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]